/* Auto-generated by cbindgen. Do not edit. */

#ifndef HOLOGRAM_H
#define HOLOGRAM_H

/* Warning: this file is autogenously generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI-friendly graph builder (mutable, not consuming).
 */
typedef struct HologramgramGraphBuilder HologramGraphBuilder;

/**
 * Return the last error code (0 if none).
 *
 * # Safety
 * Safe to call from any thread.
 */
int32_t hologram_last_error(void);

/**
 * Return a pointer to the last error message (null-terminated UTF-8).
 *
 * The returned pointer is valid until the next FFI call on this thread.
 * Returns null if no error is set.
 *
 * # Safety
 * The caller must not free the returned pointer.
 */
const char *hologram_error_message(void);

/**
 * Create a new graph builder.
 */
struct HologramGraphBuilder *hologram_graph_builder_new(void);

/**
 * Add a named input. Returns input index (>= 0) or negative error.
 */
int32_t hologram_graph_builder_input(struct HologramGraphBuilder *builder, const char *name);

/**
 * Add a node. Returns node index (>= 0) or negative error.
 *
 * `op_kind`: 0=Input, 1=Output, 2=Prim, 3=Lut.
 * `op_param`: discriminant for Prim/Lut (ignored for Input/Output).
 */
int32_t hologram_graph_builder_node(struct HologramGraphBuilder *builder,
                                int32_t op_kind,
                                int32_t op_param);

/**
 * Add a node wired to a graph-level input. Returns node index or error.
 */
int32_t hologram_graph_builder_node_from_input(struct HologramGraphBuilder *builder,
                                           int32_t op_kind,
                                           int32_t op_param,
                                           uint32_t graph_input_idx);

/**
 * Add a node with input edges. Returns node index or negative error.
 */
int32_t hologram_graph_builder_node_with_inputs(struct HologramGraphBuilder *builder,
                                            int32_t op_kind,
                                            int32_t op_param,
                                            const uintptr_t *inputs_ptr,
                                            uintptr_t inputs_len);

/**
 * Add an edge between two builder indices.
 */
int32_t hologram_graph_builder_edge(struct HologramGraphBuilder *builder,
                                uintptr_t source,
                                uintptr_t target);

/**
 * Add a named output referencing a builder index.
 */
int32_t hologram_graph_builder_output(struct HologramGraphBuilder *builder,
                                  const char *name,
                                  uintptr_t node_index);

/**
 * Build the graph, consuming the builder. Returns graph handle or null.
 */
HoloGraph *hologram_graph_builder_build(struct HologramGraphBuilder *builder);

/**
 * Return the number of nodes in a graph.
 */
int32_t hologram_graph_node_count(const HoloGraph *graph);

/**
 * Free a graph builder handle.
 */
void hologram_graph_builder_free(struct HologramGraphBuilder *builder);

/**
 * Free a graph handle.
 */
void hologram_graph_free(HoloGraph *graph);

/**
 * Compile a graph into a `.holo` archive. Consumes the graph handle.
 * Returns a compilation output handle or null on error.
 */
HoloCompilationOutput *hologram_compile(HoloGraph *graph);

/**
 * Get pointer to the compiled archive bytes.
 */
const uint8_t *hologram_compilation_archive_ptr(const HoloCompilationOutput *output);

/**
 * Get length of the compiled archive bytes.
 */
uintptr_t hologram_compilation_archive_len(const HoloCompilationOutput *output);

/**
 * Get total node count from compilation stats.
 */
uint32_t hologram_compilation_stats_nodes(const HoloCompilationOutput *output);

/**
 * Get schedule level count from compilation stats.
 */
uint32_t hologram_compilation_stats_levels(const HoloCompilationOutput *output);

/**
 * Get workspace slot count from compilation stats.
 */
uint32_t hologram_compilation_stats_workspace_slots(const HoloCompilationOutput *output);

/**
 * Free a compilation output handle.
 */
void hologram_compilation_free(HoloCompilationOutput *output);

/**
 * Create a new empty inputs handle.
 */
HoloGraphInputs *hologram_inputs_new(void);

/**
 * Set input data at `index`. Copies `data_len` bytes from `data_ptr`.
 */
int32_t hologram_inputs_set(HoloGraphInputs *inputs,
                        uint32_t index,
                        const uint8_t *data_ptr,
                        uintptr_t data_len);

/**
 * Free an inputs handle.
 */
void hologram_inputs_free(HoloGraphInputs *inputs);

/**
 * Execute a compiled archive with the given inputs.
 * `archive_ptr`/`archive_len` point to the `.holo` bytes.
 * Returns an outputs handle or null on error.
 */
HoloGraphOutputs *hologram_execute_bytes(const uint8_t *archive_ptr,
                                     uintptr_t archive_len,
                                     const HoloGraphInputs *inputs);

/**
 * Number of outputs.
 */
int32_t hologram_outputs_len(const HoloGraphOutputs *outputs);

/**
 * Get output data at `index`. Writes the data pointer and length to
 * `out_ptr` and `out_len`. Returns 0 on success.
 *
 * The data is owned by the outputs handle and valid until freed.
 */
int32_t hologram_outputs_get(const HoloGraphOutputs *outputs,
                         uintptr_t index,
                         const uint8_t **out_ptr,
                         uintptr_t *out_len);

/**
 * Get the name of output at `index`. Returns a null-terminated string
 * or null if index is out of range.
 */
const char *hologram_outputs_name(const HoloGraphOutputs *outputs, uintptr_t index);

/**
 * Get output by name. Writes data pointer and length.
 */
int32_t hologram_outputs_by_name(const HoloGraphOutputs *outputs,
                             const char *name,
                             const uint8_t **out_ptr,
                             uintptr_t *out_len);

/**
 * Free an outputs handle.
 */
void hologram_outputs_free(HoloGraphOutputs *outputs);

/**
 * Embed a continuous value into a byte using the given encoding.
 *
 * `encoding_id`: 0=Angle, 1=Signed, 2=Unsigned, 3=Raw.
 * Returns the embedded byte, or 0 on error (check `hologram_last_error`).
 */
uint8_t hologram_encoding_embed(int32_t encoding_id, double value);

/**
 * Lift a byte back to a continuous value using the given encoding.
 *
 * `encoding_id`: 0=Angle, 1=Signed, 2=Unsigned, 3=Raw.
 * Returns the lifted value, or `NaN` on error.
 */
double hologram_encoding_lift(int32_t encoding_id, uint8_t byte);

/**
 * Apply a LUT operation to a byte.
 *
 * `lut_op`: discriminant index into `LutOp::ALL` (0..20).
 * Returns the result byte, or 0 on error.
 */
uint8_t hologram_lut_apply(int32_t lut_op, uint8_t byte);

/**
 * Apply a unary primitive operation to a byte.
 *
 * `prim_op`: 0=Neg, 1=Bnot, 2=Succ, 3=Pred.
 */
uint8_t hologram_prim_apply_unary(int32_t prim_op, uint8_t byte);

/**
 * Apply a binary primitive operation to two bytes.
 *
 * `prim_op`: 4=Add, 5=Sub, 6=Mul, 7=Xor, 8=And, 9=Or.
 */
uint8_t hologram_prim_apply_binary(int32_t prim_op, uint8_t a, uint8_t b);

#endif  /* HOLOGRAM_H */
