# @generated by hologram-ffi::sdk. Do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass
from typing import Final, Mapping, Sequence

@dataclass(frozen=True)
class OpSpec:
    name: str
    arity: int
    attrs: tuple[str, ...]

    dtype_policy: str
    shape_policy: str
    doc: str

f32: Final[int] = 8

REQUIRED_FEATURES: Final[tuple[str, ...]] = (
    "abi.v1",
    "archive.v2",
    "compile.empty",
    "compile.source",
    "session",
    "source-builder",
    "source-builder.const",
    "source-builder.const-ref",
    "source-builder.output-alias",
    "errors.structured",
    "errors.locations",
)

OPS: Final[Mapping[str, OpSpec]] = {
    "neg": OpSpec("neg", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "bnot": OpSpec("bnot", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "succ": OpSpec("succ", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "pred": OpSpec("pred", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "add": OpSpec("add", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "sub": OpSpec("sub", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "mul": OpSpec("mul", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "xor": OpSpec("xor", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "and": OpSpec("and", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "or": OpSpec("or", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "relu": OpSpec("relu", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "sigmoid": OpSpec("sigmoid", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "tanh": OpSpec("tanh", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "gelu": OpSpec("gelu", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "silu": OpSpec("silu", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "elu": OpSpec("elu", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "selu": OpSpec("selu", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "exp": OpSpec("exp", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "log": OpSpec("log", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "log1p": OpSpec("log1p", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "sqrt": OpSpec("sqrt", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "reciprocal": OpSpec("reciprocal", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "sin": OpSpec("sin", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "cos": OpSpec("cos", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "tan": OpSpec("tan", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "asin": OpSpec("asin", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "acos": OpSpec("acos", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "atan": OpSpec("atan", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "ceil": OpSpec("ceil", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "floor": OpSpec("floor", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "round": OpSpec("round", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "erf": OpSpec("erf", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "is_nan": OpSpec("is_nan", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "sign": OpSpec("sign", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "abs": OpSpec("abs", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "div": OpSpec("div", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "pow": OpSpec("pow", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "mod": OpSpec("mod", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "min": OpSpec("min", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "max": OpSpec("max", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "equal": OpSpec("equal", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "less": OpSpec("less", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "less_or_equal": OpSpec("less_or_equal", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "greater": OpSpec("greater", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "greater_or_equal": OpSpec("greater_or_equal", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "matmul": OpSpec("matmul", 2, (), "f32-source-builder", "rank-2-concrete", "Matrix multiplication over rank-2 tensors."),
    "gemm": OpSpec("gemm", 3, ("alpha", "alpha_bits", "beta", "beta_bits"), "f32-source-builder", "rank-2-concrete", "General matrix multiply with optional alpha and beta attrs."),
    "conv2d": OpSpec("conv2d", 2, ("stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"), "f32-source-builder", "rank-4-concrete", "2-D convolution over concrete NCHW-style tensors."),
    "conv_transpose_2d": OpSpec("conv_transpose_2d", 2, ("stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"), "f32-source-builder", "rank-4-concrete", "2-D transposed convolution over concrete tensors."),
    "im2col": OpSpec("im2col", 1, ("stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "col2im": OpSpec("col2im", 1, ("stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "layer_norm": OpSpec("layer_norm", 3, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "rms_norm": OpSpec("rms_norm", 3, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "group_norm": OpSpec("group_norm", 3, ("num_groups",), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "instance_norm": OpSpec("instance_norm", 3, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "add_rms_norm": OpSpec("add_rms_norm", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "reduce_sum": OpSpec("reduce_sum", 1, ("axes", "axes_mask", "keepdims"), "f32-source-builder", "attrs-control-output-shape", "Canonical Hologram tensor operation."),
    "reduce_mean": OpSpec("reduce_mean", 1, ("axes", "axes_mask", "keepdims"), "f32-source-builder", "attrs-control-output-shape", "Canonical Hologram tensor operation."),
    "reduce_prod": OpSpec("reduce_prod", 1, ("axes", "axes_mask", "keepdims"), "f32-source-builder", "attrs-control-output-shape", "Canonical Hologram tensor operation."),
    "reduce_min": OpSpec("reduce_min", 1, ("axes", "axes_mask", "keepdims"), "f32-source-builder", "attrs-control-output-shape", "Canonical Hologram tensor operation."),
    "reduce_max": OpSpec("reduce_max", 1, ("axes", "axes_mask", "keepdims"), "f32-source-builder", "attrs-control-output-shape", "Canonical Hologram tensor operation."),
    "reshape": OpSpec("reshape", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "transpose": OpSpec("transpose", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "concat": OpSpec("concat", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "slice": OpSpec("slice", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "softmax": OpSpec("softmax", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "log_softmax": OpSpec("log_softmax", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "max_pool_2d": OpSpec("max_pool_2d", 1, ("stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"), "f32-source-builder", "rank-4-concrete", "Canonical Hologram tensor operation."),
    "avg_pool_2d": OpSpec("avg_pool_2d", 1, ("stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"), "f32-source-builder", "rank-4-concrete", "Canonical Hologram tensor operation."),
    "global_avg_pool": OpSpec("global_avg_pool", 1, (), "f32-source-builder", "rank-4-concrete", "Canonical Hologram tensor operation."),
    "attention": OpSpec("attention", 3, ("causal", "scale", "scale_bits"), "f32-source-builder", "optional-output-shape", "Attention block with optional causal and scale attrs."),
    "fused_swiglu": OpSpec("fused_swiglu", 2, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "pad": OpSpec("pad", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "expand": OpSpec("expand", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "resize": OpSpec("resize", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "cumsum": OpSpec("cumsum", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "rotary_embedding": OpSpec("rotary_embedding", 3, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "clip": OpSpec("clip", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "lrn": OpSpec("lrn", 1, ("alpha", "alpha_bits", "beta", "beta_bits", "bias", "bias_bits", "size"), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "where": OpSpec("where", 3, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "gather": OpSpec("gather", 2, ("axis",), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "cast": OpSpec("cast", 1, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
    "dequantize": OpSpec("dequantize", 1, ("axis", "scale", "scale_bits", "quant_dtype", "zero_point"), "f32-source-builder", "optional-output-shape", "Dequantize quantized tensor values into f32."),
    "kv_cache_write": OpSpec("kv_cache_write", 3, (), "f32-source-builder", "optional-output-shape", "Canonical Hologram tensor operation."),
}

def neg(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("neg", *inputs, **attrs)

def bnot(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("bnot", *inputs, **attrs)

def succ(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("succ", *inputs, **attrs)

def pred(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("pred", *inputs, **attrs)

def add(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("add", *inputs, **attrs)

def sub(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("sub", *inputs, **attrs)

def mul(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("mul", *inputs, **attrs)

def xor(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("xor", *inputs, **attrs)

def and_(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("and", *inputs, **attrs)

def or_(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("or", *inputs, **attrs)

def relu(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("relu", *inputs, **attrs)

def sigmoid(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("sigmoid", *inputs, **attrs)

def tanh(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("tanh", *inputs, **attrs)

def gelu(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("gelu", *inputs, **attrs)

def silu(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("silu", *inputs, **attrs)

def elu(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("elu", *inputs, **attrs)

def selu(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("selu", *inputs, **attrs)

def exp(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("exp", *inputs, **attrs)

def log(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("log", *inputs, **attrs)

def log1p(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("log1p", *inputs, **attrs)

def sqrt(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("sqrt", *inputs, **attrs)

def reciprocal(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("reciprocal", *inputs, **attrs)

def sin(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("sin", *inputs, **attrs)

def cos(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("cos", *inputs, **attrs)

def tan(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("tan", *inputs, **attrs)

def asin(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("asin", *inputs, **attrs)

def acos(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("acos", *inputs, **attrs)

def atan(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("atan", *inputs, **attrs)

def ceil(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("ceil", *inputs, **attrs)

def floor(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("floor", *inputs, **attrs)

def round(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("round", *inputs, **attrs)

def erf(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("erf", *inputs, **attrs)

def is_nan(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("is_nan", *inputs, **attrs)

def sign(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("sign", *inputs, **attrs)

def abs(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("abs", *inputs, **attrs)

def div(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("div", *inputs, **attrs)

def pow(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("pow", *inputs, **attrs)

def mod(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("mod", *inputs, **attrs)

def min(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("min", *inputs, **attrs)

def max(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("max", *inputs, **attrs)

def equal(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("equal", *inputs, **attrs)

def less(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("less", *inputs, **attrs)

def less_or_equal(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("less_or_equal", *inputs, **attrs)

def greater(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("greater", *inputs, **attrs)

def greater_or_equal(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("greater_or_equal", *inputs, **attrs)

def matmul(tensor, *inputs, **attrs):
    """Matrix multiplication over rank-2 tensors."""
    return tensor.op("matmul", *inputs, **attrs)

def gemm(tensor, *inputs, **attrs):
    """General matrix multiply with optional alpha and beta attrs."""
    return tensor.op("gemm", *inputs, **attrs)

def conv2d(tensor, *inputs, **attrs):
    """2-D convolution over concrete NCHW-style tensors."""
    return tensor.op("conv2d", *inputs, **attrs)

def conv_transpose_2d(tensor, *inputs, **attrs):
    """2-D transposed convolution over concrete tensors."""
    return tensor.op("conv_transpose_2d", *inputs, **attrs)

def im2col(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("im2col", *inputs, **attrs)

def col2im(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("col2im", *inputs, **attrs)

def layer_norm(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("layer_norm", *inputs, **attrs)

def rms_norm(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("rms_norm", *inputs, **attrs)

def group_norm(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("group_norm", *inputs, **attrs)

def instance_norm(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("instance_norm", *inputs, **attrs)

def add_rms_norm(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("add_rms_norm", *inputs, **attrs)

def reduce_sum(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("reduce_sum", *inputs, **attrs)

def reduce_mean(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("reduce_mean", *inputs, **attrs)

def reduce_prod(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("reduce_prod", *inputs, **attrs)

def reduce_min(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("reduce_min", *inputs, **attrs)

def reduce_max(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("reduce_max", *inputs, **attrs)

def reshape(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("reshape", *inputs, **attrs)

def transpose(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("transpose", *inputs, **attrs)

def concat(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("concat", *inputs, **attrs)

def slice(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("slice", *inputs, **attrs)

def softmax(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("softmax", *inputs, **attrs)

def log_softmax(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("log_softmax", *inputs, **attrs)

def max_pool_2d(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("max_pool_2d", *inputs, **attrs)

def avg_pool_2d(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("avg_pool_2d", *inputs, **attrs)

def global_avg_pool(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("global_avg_pool", *inputs, **attrs)

def attention(tensor, *inputs, **attrs):
    """Attention block with optional causal and scale attrs."""
    return tensor.op("attention", *inputs, **attrs)

def fused_swiglu(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("fused_swiglu", *inputs, **attrs)

def pad(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("pad", *inputs, **attrs)

def expand(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("expand", *inputs, **attrs)

def resize(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("resize", *inputs, **attrs)

def cumsum(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("cumsum", *inputs, **attrs)

def rotary_embedding(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("rotary_embedding", *inputs, **attrs)

def clip(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("clip", *inputs, **attrs)

def lrn(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("lrn", *inputs, **attrs)

def where(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("where", *inputs, **attrs)

def gather(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("gather", *inputs, **attrs)

def cast(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("cast", *inputs, **attrs)

def dequantize(tensor, *inputs, **attrs):
    """Dequantize quantized tensor values into f32."""
    return tensor.op("dequantize", *inputs, **attrs)

def kv_cache_write(tensor, *inputs, **attrs):
    """Canonical Hologram tensor operation."""
    return tensor.op("kv_cache_write", *inputs, **attrs)

def op_names() -> tuple[str, ...]:
    return tuple(OPS)

def op_attrs(name: str) -> tuple[str, ...]:
    return OPS[name].attrs

def op_call(builder, output: str, op: str, inputs: Sequence[str], **attrs):
    return builder.op(op, list(inputs), as_=output, **attrs)
