//! Generated SDK binding metadata.

use hologram_compiler::source;
use hologram_graph::OpKind;

/// Low-level SDK dtype metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SdkDType {
    /// SDK-visible dtype name.
    pub name: &'static str,
    /// ABI dtype id.
    pub id: u8,
}

/// Low-level SDK op metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SdkOp {
    /// Canonical op kind.
    pub kind: OpKind,
    /// Stable snake-case op name.
    pub name: &'static str,
    /// Number of primary tensor operands.
    pub arity: u8,
    /// Accepted source/SDK attribute names.
    pub attrs: &'static [&'static str],
    /// Source-builder dtype policy.
    pub dtype_policy: &'static str,
    /// Source-builder shape policy.
    pub shape_policy: &'static str,
    /// Short generated documentation string.
    pub doc: &'static str,
}

/// Dtypes currently accepted by the source-builder ABI.
pub const DTYPES: &[SdkDType] = &[SdkDType { name: "f32", id: 8 }];

/// Feature strings SDKs should probe before optional calls.
pub const FEATURES: &[&str] = &[
    "abi.v1",
    "archive.v2",
    "compile.empty",
    "compile.source",
    "session",
    "source-builder",
    "source-builder.const",
    "source-builder.const-ref",
    "source-builder.output-alias",
    "errors.structured",
    "errors.locations",
];

/// Iterate generated op metadata from the canonical op catalog.
pub fn ops() -> impl Iterator<Item = SdkOp> {
    OpKind::ALL.iter().copied().map(|kind| SdkOp {
        kind,
        name: kind.name(),
        arity: kind.primary_arity(),
        attrs: source::op_attr_names(kind),
        dtype_policy: dtype_policy(kind),
        shape_policy: shape_policy(kind),
        doc: op_doc(kind),
    })
}

/// Generate the checked-in low-level Python binding module.
#[must_use]
pub fn generate_python() -> String {
    let mut out = generated_header("#");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Final, Mapping, Sequence\n\n");
    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class OpSpec:\n");
    out.push_str("    name: str\n");
    out.push_str("    arity: int\n");
    out.push_str("    attrs: tuple[str, ...]\n\n");
    out.push_str("    dtype_policy: str\n");
    out.push_str("    shape_policy: str\n");
    out.push_str("    doc: str\n\n");
    push_python_constants(&mut out);
    push_python_ops(&mut out);
    push_python_op_wrappers(&mut out);
    push_python_helpers(&mut out);
    out
}

/// Generate the checked-in low-level TypeScript declaration module.
#[must_use]
pub fn generate_typescript() -> String {
    let mut out = generated_header("//");
    push_ts_constants(&mut out);
    push_ts_types(&mut out);
    push_ts_ops(&mut out);
    push_ts_helpers(&mut out);
    out
}

fn generated_header(prefix: &str) -> String {
    format!("{prefix} @generated by hologram-ffi::sdk. Do not edit by hand.\n\n")
}

fn push_python_constants(out: &mut String) {
    for dtype in DTYPES {
        out.push_str(&format!("{}: Final[int] = {}\n", dtype.name, dtype.id));
    }
    out.push('\n');
    out.push_str("REQUIRED_FEATURES: Final[tuple[str, ...]] = (\n");
    for feature in FEATURES {
        out.push_str(&format!("    \"{feature}\",\n"));
    }
    out.push_str(")\n\n");
}

fn push_python_ops(out: &mut String) {
    out.push_str("OPS: Final[Mapping[str, OpSpec]] = {\n");
    for op in ops() {
        out.push_str(&format!(
            "    \"{}\": OpSpec(\"{}\", {}, {}, \"{}\", \"{}\", \"{}\"),\n",
            op.name,
            op.name,
            op.arity,
            python_tuple(op.attrs),
            op.dtype_policy,
            op.shape_policy,
            op.doc
        ));
    }
    out.push_str("}\n\n");
}

fn push_python_helpers(out: &mut String) {
    out.push_str("def op_names() -> tuple[str, ...]:\n");
    out.push_str("    return tuple(OPS)\n\n");
    out.push_str("def op_attrs(name: str) -> tuple[str, ...]:\n");
    out.push_str("    return OPS[name].attrs\n\n");
    out.push_str("def op_call(builder, output: str, op: str, inputs: Sequence[str], **attrs):\n");
    out.push_str("    return builder.op(op, list(inputs), as_=output, **attrs)\n");
}

fn push_ts_constants(out: &mut String) {
    for dtype in DTYPES {
        out.push_str(&format!(
            "export const {} = {} as const;\n",
            dtype.name, dtype.id
        ));
    }
    out.push_str("\nexport const REQUIRED_FEATURES = [\n");
    for feature in FEATURES {
        out.push_str(&format!("  \"{feature}\",\n"));
    }
    out.push_str("] as const;\n\n");
}

fn push_ts_types(out: &mut String) {
    out.push_str("export type DType = typeof f32;\n");
    out.push_str("export type Feature = (typeof REQUIRED_FEATURES)[number];\n\n");
    out.push_str("export interface OpSpec {\n");
    out.push_str("  readonly name: OpName;\n");
    out.push_str("  readonly arity: number;\n");
    out.push_str("  readonly attrs: readonly string[];\n");
    out.push_str("  readonly dtypePolicy: string;\n");
    out.push_str("  readonly shapePolicy: string;\n");
    out.push_str("  readonly doc: string;\n");
    out.push_str("}\n\n");
}

fn push_ts_ops(out: &mut String) {
    out.push_str("export const OPS = {\n");
    for op in ops() {
        out.push_str(&format!(
            "  {}: {{ name: \"{}\", arity: {}, attrs: {}, dtypePolicy: \"{}\", shapePolicy: \"{}\", doc: \"{}\" }},\n",
            ts_key(op.name),
            op.name,
            op.arity,
            ts_array(op.attrs),
            op.dtype_policy,
            op.shape_policy,
            op.doc
        ));
    }
    out.push_str("} as const;\n\n");
}

fn push_ts_helpers(out: &mut String) {
    out.push_str("export type OpName = keyof typeof OPS;\n");
    out.push_str("export type OpArity<Name extends OpName> = (typeof OPS)[Name][\"arity\"];\n");
    out.push_str(
        "export type OpAttrName<Name extends OpName> = (typeof OPS)[Name][\"attrs\"][number];\n",
    );
    out.push_str("export type OpOptionsFor<Name extends OpName> = { readonly [K in OpAttrName<Name>]?: unknown };\n");
    out.push_str("export type TensorRef = string;\n");
    out.push_str("export type OpAttrs = Record<string, unknown>;\n\n");
    push_ts_tensor_methods(out);
    out.push_str("export interface LowLevelGraphBuilder {\n");
    out.push_str("  op(output: TensorRef, op: OpName, inputs: readonly TensorRef[], attrs?: OpAttrs): TensorRef;\n");
    out.push_str("}\n\n");
    out.push_str("export function opCall(\n");
    out.push_str("  builder: LowLevelGraphBuilder,\n");
    out.push_str("  output: TensorRef,\n");
    out.push_str("  op: OpName,\n");
    out.push_str("  inputs: readonly TensorRef[],\n");
    out.push_str("  attrs: OpAttrs = {},\n");
    out.push_str("): TensorRef {\n");
    out.push_str("  return builder.op(output, op, inputs, attrs);\n");
    out.push_str("}\n");
}

fn push_python_op_wrappers(out: &mut String) {
    for op in ops() {
        out.push_str(&format!(
            "def {}(tensor, *inputs, **attrs):\n",
            python_ident(op.name)
        ));
        out.push_str(&format!("    \"\"\"{}\"\"\"\n", op.doc));
        out.push_str(&format!(
            "    return tensor.op(\"{}\", *inputs, **attrs)\n\n",
            op.name
        ));
    }
}

fn python_ident(name: &str) -> String {
    if python_keyword(name) {
        return format!("{name}_");
    }
    String::from(name)
}

fn python_keyword(name: &str) -> bool {
    matches!(
        name,
        "False"
            | "None"
            | "True"
            | "and"
            | "as"
            | "assert"
            | "async"
            | "await"
            | "break"
            | "class"
            | "continue"
            | "def"
            | "del"
            | "elif"
            | "else"
            | "except"
            | "finally"
            | "for"
            | "from"
            | "global"
            | "if"
            | "import"
            | "in"
            | "is"
            | "lambda"
            | "nonlocal"
            | "not"
            | "or"
            | "pass"
            | "raise"
            | "return"
            | "try"
            | "while"
            | "with"
            | "yield"
    )
}

fn push_ts_tensor_methods(out: &mut String) {
    out.push_str(
        "export interface GeneratedTensorMethods<TTensor, TInput, TAttrs extends OpAttrs = OpAttrs> {\n",
    );
    for op in ops() {
        out.push_str(&format!("  {}(", ts_key(op.name)));
        push_ts_method_args(out, op.name, op.arity);
        out.push_str("): TTensor;\n");
    }
    out.push_str("}\n\n");
}

fn push_ts_method_args(out: &mut String, op_name: &str, arity: u8) {
    let extra_inputs = arity.saturating_sub(1);
    for i in 0..extra_inputs {
        out.push_str(&format!("input{i}: TInput, "));
    }
    out.push_str(&format!("attrs?: TAttrs & OpOptionsFor<\"{op_name}\">"));
}

fn python_tuple(values: &[&str]) -> String {
    match values {
        [] => String::from("()"),
        [only] => format!("(\"{only}\",)"),
        _ => format!(
            "({})",
            values
                .iter()
                .map(|value| format!("\"{value}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn ts_array(values: &[&str]) -> String {
    if values.is_empty() {
        return String::from("[] as const");
    }
    format!(
        "[{}] as const",
        values
            .iter()
            .map(|value| format!("\"{value}\""))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn ts_key(name: &str) -> String {
    if name
        .chars()
        .all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
    {
        return name.to_string();
    }
    format!("\"{name}\"")
}

fn dtype_policy(_kind: OpKind) -> &'static str {
    "f32-source-builder"
}

fn shape_policy(kind: OpKind) -> &'static str {
    use OpKind as K;
    match kind {
        K::MatMul | K::Gemm => "rank-2-concrete",
        K::Conv2d | K::ConvTranspose2d | K::MaxPool2d | K::AvgPool2d | K::GlobalAvgPool => {
            "rank-4-concrete"
        }
        K::ReduceSum | K::ReduceMean | K::ReduceProd | K::ReduceMin | K::ReduceMax => {
            "attrs-control-output-shape"
        }
        _ => "optional-output-shape",
    }
}

fn op_doc(kind: OpKind) -> &'static str {
    match kind {
        OpKind::MatMul => "Matrix multiplication over rank-2 tensors.",
        OpKind::Gemm => "General matrix multiply with optional alpha and beta attrs.",
        OpKind::Conv2d => "2-D convolution over concrete NCHW-style tensors.",
        OpKind::ConvTranspose2d => "2-D transposed convolution over concrete tensors.",
        OpKind::Attention => "Attention block with optional causal and scale attrs.",
        OpKind::Dequantize => "Dequantize quantized tensor values into f32.",
        _ => "Canonical Hologram tensor operation.",
    }
}
