// @generated by hologram-ffi::sdk. Do not edit by hand.

export const f32 = 8 as const;

export const REQUIRED_FEATURES = [
  "abi.v1",
  "archive.v2",
  "compile.empty",
  "compile.source",
  "session",
  "source-builder",
  "source-builder.const",
  "source-builder.const-ref",
  "source-builder.output-alias",
  "errors.structured",
  "errors.locations",
] as const;

export type DType = typeof f32;
export type Feature = (typeof REQUIRED_FEATURES)[number];

export interface OpSpec {
  readonly name: OpName;
  readonly arity: number;
  readonly attrs: readonly string[];
  readonly dtypePolicy: string;
  readonly shapePolicy: string;
  readonly doc: string;
}

export const OPS = {
  neg: { name: "neg", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  bnot: { name: "bnot", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  succ: { name: "succ", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  pred: { name: "pred", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  add: { name: "add", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  sub: { name: "sub", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  mul: { name: "mul", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  xor: { name: "xor", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  and: { name: "and", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  or: { name: "or", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  relu: { name: "relu", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  sigmoid: { name: "sigmoid", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  tanh: { name: "tanh", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  gelu: { name: "gelu", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  silu: { name: "silu", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  elu: { name: "elu", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  selu: { name: "selu", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  exp: { name: "exp", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  log: { name: "log", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  log1p: { name: "log1p", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  sqrt: { name: "sqrt", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  reciprocal: { name: "reciprocal", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  sin: { name: "sin", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  cos: { name: "cos", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  tan: { name: "tan", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  asin: { name: "asin", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  acos: { name: "acos", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  atan: { name: "atan", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  ceil: { name: "ceil", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  floor: { name: "floor", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  round: { name: "round", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  erf: { name: "erf", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  is_nan: { name: "is_nan", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  sign: { name: "sign", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  abs: { name: "abs", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  div: { name: "div", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  pow: { name: "pow", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  mod: { name: "mod", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  min: { name: "min", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  max: { name: "max", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  equal: { name: "equal", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  less: { name: "less", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  less_or_equal: { name: "less_or_equal", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  greater: { name: "greater", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  greater_or_equal: { name: "greater_or_equal", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  matmul: { name: "matmul", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "rank-2-concrete", doc: "Matrix multiplication over rank-2 tensors." },
  gemm: { name: "gemm", arity: 3, attrs: ["alpha", "alpha_bits", "beta", "beta_bits"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "rank-2-concrete", doc: "General matrix multiply with optional alpha and beta attrs." },
  conv2d: { name: "conv2d", arity: 2, attrs: ["stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "rank-4-concrete", doc: "2-D convolution over concrete NCHW-style tensors." },
  conv_transpose_2d: { name: "conv_transpose_2d", arity: 2, attrs: ["stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "rank-4-concrete", doc: "2-D transposed convolution over concrete tensors." },
  im2col: { name: "im2col", arity: 1, attrs: ["stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  col2im: { name: "col2im", arity: 1, attrs: ["stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  layer_norm: { name: "layer_norm", arity: 3, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  rms_norm: { name: "rms_norm", arity: 3, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  group_norm: { name: "group_norm", arity: 3, attrs: ["num_groups"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  instance_norm: { name: "instance_norm", arity: 3, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  add_rms_norm: { name: "add_rms_norm", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  reduce_sum: { name: "reduce_sum", arity: 1, attrs: ["axes", "axes_mask", "keepdims"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "attrs-control-output-shape", doc: "Canonical Hologram tensor operation." },
  reduce_mean: { name: "reduce_mean", arity: 1, attrs: ["axes", "axes_mask", "keepdims"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "attrs-control-output-shape", doc: "Canonical Hologram tensor operation." },
  reduce_prod: { name: "reduce_prod", arity: 1, attrs: ["axes", "axes_mask", "keepdims"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "attrs-control-output-shape", doc: "Canonical Hologram tensor operation." },
  reduce_min: { name: "reduce_min", arity: 1, attrs: ["axes", "axes_mask", "keepdims"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "attrs-control-output-shape", doc: "Canonical Hologram tensor operation." },
  reduce_max: { name: "reduce_max", arity: 1, attrs: ["axes", "axes_mask", "keepdims"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "attrs-control-output-shape", doc: "Canonical Hologram tensor operation." },
  reshape: { name: "reshape", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  transpose: { name: "transpose", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  concat: { name: "concat", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  slice: { name: "slice", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  softmax: { name: "softmax", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  log_softmax: { name: "log_softmax", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  max_pool_2d: { name: "max_pool_2d", arity: 1, attrs: ["stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "rank-4-concrete", doc: "Canonical Hologram tensor operation." },
  avg_pool_2d: { name: "avg_pool_2d", arity: 1, attrs: ["stride", "strides", "pad", "pads", "padding", "kernel", "k", "stride_h", "stride_w", "pad_h", "pad_w", "k_h", "k_w"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "rank-4-concrete", doc: "Canonical Hologram tensor operation." },
  global_avg_pool: { name: "global_avg_pool", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "rank-4-concrete", doc: "Canonical Hologram tensor operation." },
  attention: { name: "attention", arity: 3, attrs: ["causal", "scale", "scale_bits"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Attention block with optional causal and scale attrs." },
  fused_swiglu: { name: "fused_swiglu", arity: 2, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  pad: { name: "pad", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  expand: { name: "expand", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  resize: { name: "resize", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  cumsum: { name: "cumsum", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  rotary_embedding: { name: "rotary_embedding", arity: 3, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  clip: { name: "clip", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  lrn: { name: "lrn", arity: 1, attrs: ["alpha", "alpha_bits", "beta", "beta_bits", "bias", "bias_bits", "size"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  where: { name: "where", arity: 3, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  gather: { name: "gather", arity: 2, attrs: ["axis"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  cast: { name: "cast", arity: 1, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
  dequantize: { name: "dequantize", arity: 1, attrs: ["axis", "scale", "scale_bits", "quant_dtype", "zero_point"] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Dequantize quantized tensor values into f32." },
  kv_cache_write: { name: "kv_cache_write", arity: 3, attrs: [] as const, dtypePolicy: "f32-source-builder", shapePolicy: "optional-output-shape", doc: "Canonical Hologram tensor operation." },
} as const;

export type OpName = keyof typeof OPS;
export type OpArity<Name extends OpName> = (typeof OPS)[Name]["arity"];
export type OpAttrName<Name extends OpName> = (typeof OPS)[Name]["attrs"][number];
export type OpOptionsFor<Name extends OpName> = { readonly [K in OpAttrName<Name>]?: unknown };
export type TensorRef = string;
export type OpAttrs = Record<string, unknown>;

export interface GeneratedTensorMethods<TTensor, TInput, TAttrs extends OpAttrs = OpAttrs> {
  neg(attrs?: TAttrs & OpOptionsFor<"neg">): TTensor;
  bnot(attrs?: TAttrs & OpOptionsFor<"bnot">): TTensor;
  succ(attrs?: TAttrs & OpOptionsFor<"succ">): TTensor;
  pred(attrs?: TAttrs & OpOptionsFor<"pred">): TTensor;
  add(input0: TInput, attrs?: TAttrs & OpOptionsFor<"add">): TTensor;
  sub(input0: TInput, attrs?: TAttrs & OpOptionsFor<"sub">): TTensor;
  mul(input0: TInput, attrs?: TAttrs & OpOptionsFor<"mul">): TTensor;
  xor(input0: TInput, attrs?: TAttrs & OpOptionsFor<"xor">): TTensor;
  and(input0: TInput, attrs?: TAttrs & OpOptionsFor<"and">): TTensor;
  or(input0: TInput, attrs?: TAttrs & OpOptionsFor<"or">): TTensor;
  relu(attrs?: TAttrs & OpOptionsFor<"relu">): TTensor;
  sigmoid(attrs?: TAttrs & OpOptionsFor<"sigmoid">): TTensor;
  tanh(attrs?: TAttrs & OpOptionsFor<"tanh">): TTensor;
  gelu(attrs?: TAttrs & OpOptionsFor<"gelu">): TTensor;
  silu(attrs?: TAttrs & OpOptionsFor<"silu">): TTensor;
  elu(attrs?: TAttrs & OpOptionsFor<"elu">): TTensor;
  selu(attrs?: TAttrs & OpOptionsFor<"selu">): TTensor;
  exp(attrs?: TAttrs & OpOptionsFor<"exp">): TTensor;
  log(attrs?: TAttrs & OpOptionsFor<"log">): TTensor;
  log1p(attrs?: TAttrs & OpOptionsFor<"log1p">): TTensor;
  sqrt(attrs?: TAttrs & OpOptionsFor<"sqrt">): TTensor;
  reciprocal(attrs?: TAttrs & OpOptionsFor<"reciprocal">): TTensor;
  sin(attrs?: TAttrs & OpOptionsFor<"sin">): TTensor;
  cos(attrs?: TAttrs & OpOptionsFor<"cos">): TTensor;
  tan(attrs?: TAttrs & OpOptionsFor<"tan">): TTensor;
  asin(attrs?: TAttrs & OpOptionsFor<"asin">): TTensor;
  acos(attrs?: TAttrs & OpOptionsFor<"acos">): TTensor;
  atan(attrs?: TAttrs & OpOptionsFor<"atan">): TTensor;
  ceil(attrs?: TAttrs & OpOptionsFor<"ceil">): TTensor;
  floor(attrs?: TAttrs & OpOptionsFor<"floor">): TTensor;
  round(attrs?: TAttrs & OpOptionsFor<"round">): TTensor;
  erf(attrs?: TAttrs & OpOptionsFor<"erf">): TTensor;
  is_nan(attrs?: TAttrs & OpOptionsFor<"is_nan">): TTensor;
  sign(attrs?: TAttrs & OpOptionsFor<"sign">): TTensor;
  abs(attrs?: TAttrs & OpOptionsFor<"abs">): TTensor;
  div(input0: TInput, attrs?: TAttrs & OpOptionsFor<"div">): TTensor;
  pow(input0: TInput, attrs?: TAttrs & OpOptionsFor<"pow">): TTensor;
  mod(input0: TInput, attrs?: TAttrs & OpOptionsFor<"mod">): TTensor;
  min(input0: TInput, attrs?: TAttrs & OpOptionsFor<"min">): TTensor;
  max(input0: TInput, attrs?: TAttrs & OpOptionsFor<"max">): TTensor;
  equal(input0: TInput, attrs?: TAttrs & OpOptionsFor<"equal">): TTensor;
  less(input0: TInput, attrs?: TAttrs & OpOptionsFor<"less">): TTensor;
  less_or_equal(input0: TInput, attrs?: TAttrs & OpOptionsFor<"less_or_equal">): TTensor;
  greater(input0: TInput, attrs?: TAttrs & OpOptionsFor<"greater">): TTensor;
  greater_or_equal(input0: TInput, attrs?: TAttrs & OpOptionsFor<"greater_or_equal">): TTensor;
  matmul(input0: TInput, attrs?: TAttrs & OpOptionsFor<"matmul">): TTensor;
  gemm(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"gemm">): TTensor;
  conv2d(input0: TInput, attrs?: TAttrs & OpOptionsFor<"conv2d">): TTensor;
  conv_transpose_2d(input0: TInput, attrs?: TAttrs & OpOptionsFor<"conv_transpose_2d">): TTensor;
  im2col(attrs?: TAttrs & OpOptionsFor<"im2col">): TTensor;
  col2im(attrs?: TAttrs & OpOptionsFor<"col2im">): TTensor;
  layer_norm(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"layer_norm">): TTensor;
  rms_norm(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"rms_norm">): TTensor;
  group_norm(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"group_norm">): TTensor;
  instance_norm(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"instance_norm">): TTensor;
  add_rms_norm(input0: TInput, attrs?: TAttrs & OpOptionsFor<"add_rms_norm">): TTensor;
  reduce_sum(attrs?: TAttrs & OpOptionsFor<"reduce_sum">): TTensor;
  reduce_mean(attrs?: TAttrs & OpOptionsFor<"reduce_mean">): TTensor;
  reduce_prod(attrs?: TAttrs & OpOptionsFor<"reduce_prod">): TTensor;
  reduce_min(attrs?: TAttrs & OpOptionsFor<"reduce_min">): TTensor;
  reduce_max(attrs?: TAttrs & OpOptionsFor<"reduce_max">): TTensor;
  reshape(attrs?: TAttrs & OpOptionsFor<"reshape">): TTensor;
  transpose(attrs?: TAttrs & OpOptionsFor<"transpose">): TTensor;
  concat(input0: TInput, attrs?: TAttrs & OpOptionsFor<"concat">): TTensor;
  slice(attrs?: TAttrs & OpOptionsFor<"slice">): TTensor;
  softmax(attrs?: TAttrs & OpOptionsFor<"softmax">): TTensor;
  log_softmax(attrs?: TAttrs & OpOptionsFor<"log_softmax">): TTensor;
  max_pool_2d(attrs?: TAttrs & OpOptionsFor<"max_pool_2d">): TTensor;
  avg_pool_2d(attrs?: TAttrs & OpOptionsFor<"avg_pool_2d">): TTensor;
  global_avg_pool(attrs?: TAttrs & OpOptionsFor<"global_avg_pool">): TTensor;
  attention(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"attention">): TTensor;
  fused_swiglu(input0: TInput, attrs?: TAttrs & OpOptionsFor<"fused_swiglu">): TTensor;
  pad(attrs?: TAttrs & OpOptionsFor<"pad">): TTensor;
  expand(attrs?: TAttrs & OpOptionsFor<"expand">): TTensor;
  resize(attrs?: TAttrs & OpOptionsFor<"resize">): TTensor;
  cumsum(attrs?: TAttrs & OpOptionsFor<"cumsum">): TTensor;
  rotary_embedding(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"rotary_embedding">): TTensor;
  clip(attrs?: TAttrs & OpOptionsFor<"clip">): TTensor;
  lrn(attrs?: TAttrs & OpOptionsFor<"lrn">): TTensor;
  where(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"where">): TTensor;
  gather(input0: TInput, attrs?: TAttrs & OpOptionsFor<"gather">): TTensor;
  cast(attrs?: TAttrs & OpOptionsFor<"cast">): TTensor;
  dequantize(attrs?: TAttrs & OpOptionsFor<"dequantize">): TTensor;
  kv_cache_write(input0: TInput, input1: TInput, attrs?: TAttrs & OpOptionsFor<"kv_cache_write">): TTensor;
}

export interface LowLevelGraphBuilder {
  op(output: TensorRef, op: OpName, inputs: readonly TensorRef[], attrs?: OpAttrs): TensorRef;
}

export function opCall(
  builder: LowLevelGraphBuilder,
  output: TensorRef,
  op: OpName,
  inputs: readonly TensorRef[],
  attrs: OpAttrs = {},
): TensorRef {
  return builder.op(output, op, inputs, attrs);
}
