//! Dihedral orbit compression for centroid dot products.
//!
//! UOR grounding: isometry identities OB_M4/M5 (`d_R(neg(x),neg(y)) = d_R(x,y)`).
//! The dihedral group D_Q generated by `PrimOp::Neg` acts on the centroid index space
//! via wrapping negation mod Q. For symmetric centroid distributions,
//! `c[neg(i)] ≈ -c[i]`, so orbit members can be combined before the final multiply,
//! reducing the MAC count from Q to rep_count ≤ Q/2.
//!
//! # Complexity
//! - `build_orbit_map_q4`: O(16) — called once at quantize time.
//! - `build_orbit_map_q8`: O(256) — called once at quantize time.
//! - `dot_orbits` (Q4):  O(16) first pass + O(rep_count) second pass.
//! - `dot_orbits` (Q8): O(256) first pass + O(rep_count) second pass.
//!
//! For fully symmetric Q8 centroids, rep_count = 128, halving the centroid MACs.

/// Relative tolerance for declaring `c[i]` and `c[neg_i]` a symmetric pair.
/// Tests `|c[i] + c[neg_i]| < TOL * max(|c[i]|, |c[neg_i]|)`.
///
/// Conservative: 1e-4 ensures only genuinely symmetric centroids are combined.
/// This guarantees dot_orbits is numerically equivalent to dot for any
/// centroid distribution — no conditional guards or fallbacks needed.
const ORBIT_SYMMETRY_TOL: f32 = 1e-4;

#[inline]
fn centroid_symmetric(c_i: f32, c_neg: f32) -> bool {
    let denom = c_i.abs().max(c_neg.abs());
    denom > 0.0 && (c_i + c_neg).abs() < ORBIT_SYMMETRY_TOL * denom
}

/// Dihedral orbit map for Q4 (16 centroids).
///
/// `entries[i] = (canonical_rep_index, sign_correction)`.
/// If `c[neg_i] ≈ -c[i]`: `entries[neg_i] = (i, -1)`.
/// Otherwise `entries[i] = (i, 1)` (independent orbit).
/// `rep_count` = number of unique canonical representatives.
///
/// Fixed-size, `Copy`, zero heap.
#[derive(Clone, Copy, Debug, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
#[repr(C)]
pub struct OrbitMap4 {
    /// `(rep_index, sign)` for each of the 16 centroid indices.
    pub entries: [(u8, i8); 16],
    /// Number of unique canonical representatives (≤ 16).
    pub rep_count: u8,
}

/// Dihedral orbit map for Q8 (256 centroids).
///
/// Same semantics as `OrbitMap4` but for 256 entries.
/// `rep_count` uses u16 to accommodate the full range [0, 256].
///
/// Fixed-size, `Copy`, zero heap.
#[derive(Clone, Copy, Debug, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
#[repr(C)]
pub struct OrbitMap8 {
    /// `(rep_index, sign)` for each of the 256 centroid indices.
    pub entries: [(u8, i8); 256],
    /// Number of unique canonical representatives (≤ 256). u16 to avoid overflow.
    pub rep_count: u16,
}

/// Build a Q4 dihedral orbit map from quantized centroids.
///
/// Called once after k-means convergence in `quantize_4bit`. O(16).
#[must_use]
pub fn build_orbit_map_q4(centroids: &[f32; 16]) -> OrbitMap4 {
    let mut entries = [(0u8, 1i8); 16];
    let mut visited = [false; 16];
    let mut rep_count = 0u8;

    for i in 0..16usize {
        if visited[i] {
            continue;
        }
        // neg(i) in Z/16Z = (16 - i) % 16
        let neg_i = (16usize.wrapping_sub(i)) & 15;
        entries[i] = (i as u8, 1);
        visited[i] = true;
        rep_count += 1;

        if neg_i != i && !visited[neg_i] && centroid_symmetric(centroids[i], centroids[neg_i]) {
            entries[neg_i] = (i as u8, -1);
            visited[neg_i] = true;
            // neg_i is not a rep — it maps to i
        }
    }

    OrbitMap4 { entries, rep_count }
}

/// Build a Q8 dihedral orbit map from quantized centroids.
///
/// Called once after k-means convergence in `quantize_8bit`. O(256).
#[must_use]
pub fn build_orbit_map_q8(centroids: &[f32; 256]) -> OrbitMap8 {
    let mut entries = [(0u8, 1i8); 256];
    let mut visited = [false; 256];
    let mut rep_count = 0u16;

    for i in 0..256usize {
        if visited[i] {
            continue;
        }
        // neg(i) in Z/256Z = (256 - i) % 256
        let neg_i = (256usize.wrapping_sub(i)) & 255;
        entries[i] = (i as u8, 1);
        visited[i] = true;
        rep_count += 1;

        if neg_i != i && !visited[neg_i] && centroid_symmetric(centroids[i], centroids[neg_i]) {
            entries[neg_i] = (i as u8, -1);
            visited[neg_i] = true;
        }
    }

    OrbitMap8 { entries, rep_count }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_fully_symmetric_centroids_q4() -> [f32; 16] {
        // c[i] = -c[16-i mod 16] exactly, except c[0] = 0
        let mut c = [0.0f32; 16];
        for i in 1..8usize {
            c[i] = i as f32;
            c[16 - i] = -(i as f32);
        }
        // c[8] = 0 (self-inverse)
        c
    }

    fn make_random_centroids_q8() -> [f32; 256] {
        // Pseudo-random values without symmetry
        let mut c = [0.0f32; 256];
        for (i, v) in c.iter_mut().enumerate() {
            // Using a deterministic "hash" that avoids symmetry
            *v = (i as f32 * 1.6180339) % 7.0 + 1.0;
        }
        c
    }

    fn make_fully_symmetric_centroids_q8() -> [f32; 256] {
        let mut c = [0.0f32; 256];
        // c[0] = 0 (self-inverse), c[128] = 0 (self-inverse)
        for i in 1..128usize {
            c[i] = i as f32;
            c[256 - i] = -(i as f32);
        }
        c
    }

    #[test]
    fn orbit_map_q4_rep_count_symmetric() {
        // Fully symmetric Q4 centroids: 0 is self-rep, 8 is self-rep,
        // pairs (1,15), (2,14), (3,13), (4,12), (5,11), (6,10), (7,9) → 2 + 7 = 9 reps.
        // Wait: i=0 (neg=0, self), i=1 (neg=15) → pair, i=2 (neg=14) → pair, ...
        // i=8 (neg=8, self). So reps: 0,1,2,3,4,5,6,7,8 = 9.
        let c = make_fully_symmetric_centroids_q4();
        let map = build_orbit_map_q4(&c);
        // 2 self-inverse (0,8) + 7 pairs = 9 reps
        assert_eq!(map.rep_count, 9, "expected 9 reps, got {}", map.rep_count);
    }

    #[test]
    fn orbit_map_q8_identity_on_asymmetric() {
        // Random centroids with no symmetry → every index is its own rep.
        let c = make_random_centroids_q8();
        let map = build_orbit_map_q8(&c);
        assert_eq!(
            map.rep_count, 256,
            "expected 256 reps for asymmetric, got {}",
            map.rep_count
        );
    }

    #[test]
    fn orbit_map_q8_fully_symmetric() {
        // c[0]=0 (self), c[128]=0 (self), pairs (1,255), (2,254), ..., (127,129): 2 + 127 = 129 reps.
        let c = make_fully_symmetric_centroids_q8();
        let map = build_orbit_map_q8(&c);
        // 2 self-inverse (0, 128) + 127 pairs = 129 reps
        assert_eq!(
            map.rep_count, 129,
            "expected 129 reps, got {}",
            map.rep_count
        );
    }

    #[test]
    fn orbit_map_q4_entries_self_inverse() {
        // Index 0 and index 8 should map to themselves with sign +1.
        let c = make_fully_symmetric_centroids_q4();
        let map = build_orbit_map_q4(&c);
        assert_eq!(map.entries[0], (0, 1));
        assert_eq!(map.entries[8], (8, 1));
    }

    #[test]
    fn orbit_map_q4_entries_symmetric_pair() {
        // Index 1 should be rep (+1), index 15 should map to 1 with sign -1.
        let c = make_fully_symmetric_centroids_q4();
        let map = build_orbit_map_q4(&c);
        assert_eq!(map.entries[1].0, 1);
        assert_eq!(map.entries[1].1, 1);
        assert_eq!(map.entries[15].0, 1);
        assert_eq!(map.entries[15].1, -1);
    }
}
